### ISSUE TITLE
Bug fixing suggestion

### ISSUE THREAD

**Issue by alex-sandr111** [FINDarkside/TLD-Save-Editor-3#22]
Hello! :) 
I recently stumbled upon your repo, because I was stuck with a bug in game where my spear has disappeared and I couldn't fight the bear in the Wintermute. 
So I downloaded the repo, installed the latest LTS Node.js version (v22.11.0) and started the project. 
I encountered two problems that I describe below.

First, I am playing on my MacBook (with M1 chip), so I had problems with the path to save files first. 

I had to modify src/store.ts file like the following:  
added 
`const os = require('os');` 
to the imports;
and 
replaced 
```
    if (!process.env.LOCALAPPDATA) throw new Error('LOCALAPPDATA is not set');

    const saveFolder = path.join(
      process.env.LOCALAPPDATA,
      'Hinterland',
      'TheLongDark'
    );
```
with 
`const saveFolder = path.join(os.homedir(), '.local', 'share', 'Hinterland', 'TheLongDark')`
. 

Then it worked (save files were found on the program start). I don't have a possibility to check the code on a Windows machine, that's why I don't create a pull request, but maybe you could do the needed change so that MacBook user could enjoy your amazing Save Editor too! :) 

Second, there is a problem with amount of stackable elements. If you change the amount in the according "Amount" input field, the new amount is written into the JSON as string, for example, "2". But the game expects a number there: 2 (without quotes). If you change the number manually in the JSON area, it works. Otherwise the save file will be broken and the game doesn't allow to load it. 
Unfortunately, I have never worked with Vue and don't see where the problem with quotes comes from. Could you maybe have a look at it and fix the described bugs? :)

I also want to thank you for your work and wish you a nice sunday!

Best regadrs, 
Alex

**Comment by alex-sandr111** [comment]
I created a pull request with regard to the first issue: https://github.com/FINDarkside/TLD-Save-Editor-3/pull/23

**Comment by Moumirrai** [comment]
This should solve the second issue: #24

**Comment by alex-sandr111** [comment]
@Moumirrai I checked locally and it indeed solves the problem! Thanks! :)

**Comment by FINDarkside** [comment]
Nice work both of you, I'll check these out later this week when I have time. 👍
